# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cad0a41c01b1d1a771601623a87e59af936720e2ca60285f1f5f1cc3e41cdafc34ca72e9a4d10f870aa47a5635e3e338f8eb53f9b5c2174c0ee75cc602a42a3e

test:
  secret_key_base: 1c5c2ed47c88e1b790ae2b36145408facad5ad542acb15d267c94a073d6193b5bd2a8bff7aba6a6151afa2c61cf51161189db0455f7865b6a63df9183ad3325c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
